---
- name: Download Node Exporter
  become: true
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /usr/local/src/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    checksum: sha256:{{ node_exporter_sha_checksum }}
    mode: 0644
  retries: 3
  delay: 2

- name: Unpack Node Exporter
  become: true
  ansible.builtin.unarchive:
    src: /usr/local/src/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: true

- name: Configure Node Exporter symlink
  become: true
  ansible.builtin.file:
    path: /opt/node_exporter
    src: /opt/node_exporter-{{ node_exporter_version }}.linux-amd64
    state: link

- name: Ensure Node Exporter group exists
  become: true
  ansible.builtin.group:
    name: node_exporter
    state: present
    system: true

- name: Ensure Node Exporter user exists
  become: true
  ansible.builtin.user:
    name: node_exporter
    state: present
    system: true
    home: /opt/node_exporter
    createhome: false

- name: Create folder sysconfig
  become: true
  ansible.builtin.file:
    path: /etc/sysconfig
    state: directory
    mode: 0755

- name: Set Node Exporter options definition
  become: true
  ansible.builtin.copy:
    content: "OPTIONS=\"{{ node_exporter_options | join(' ') }}\""
    dest: /etc/sysconfig/node_exporter
    mode: 0644
  when: node_exporter_options | length > 0

- name: Install Node Exporter service definition
  become: true
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
  notify: Restart node exporter

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure Node Exporter service is enabled and started
  become: true
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started
  retries: 3
  delay: 2

- name: Wait for Node Exporter to start
  ansible.builtin.wait_for:
    port: 9100
    timeout: 60
